2018-03-23 10:31:08.110 [error] <0.182.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.187.0> exit with reason normal in context child_terminated
2018-03-23 10:31:08.172 [info] <0.33.0> Application lager started on node 'server@NT-21'
2018-03-23 10:31:08.189 [info] <0.33.0> Application xmerl started on node 'server@NT-21'
2018-03-23 10:31:08.204 [info] <0.33.0> Application jsx started on node 'server@NT-21'
2018-03-23 10:31:08.259 [info] <0.33.0> Application ranch started on node 'server@NT-21'
2018-03-23 10:31:08.270 [info] <0.33.0> Application ranch_proxy_protocol started on node 'server@NT-21'
2018-03-23 10:31:08.281 [info] <0.33.0> Application recon started on node 'server@NT-21'
2018-03-23 10:31:08.281 [info] <0.33.0> Application rabbit_common started on node 'server@NT-21'
2018-03-23 10:31:08.300 [info] <0.33.0> Application amqp_client started on node 'server@NT-21'
2018-03-23 10:31:08.301 [info] <0.33.0> Application amqp started on node 'server@NT-21'
2018-03-23 10:31:08.314 [info] <0.33.0> Application poison started on node 'server@NT-21'
2018-03-23 10:31:08.344 [info] <0.33.0> Application earmark started on node 'server@NT-21'
2018-03-23 10:31:08.344 [info] <0.33.0> Application ex_doc started on node 'server@NT-21'
2018-03-23 10:31:08.345 [info] <0.33.0> Application battleships started on node 'server@NT-21'
2018-03-23 10:31:09.705 [warning] <0.32.0> lager_error_logger_h dropped 0 messages in the last second that exceeded the limit of 50 messages/sec
2018-03-23 10:31:15.560 [error] <0.291.0>@Elixir.BattleshipServer.Store:handle_info:23 gen_server <0.291.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23
2018-03-23 10:31:15.560 [error] <0.291.0>@Elixir.BattleshipServer.Store:handle_info:23 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23
2018-03-23 10:31:15.560 [error] <0.273.0>@Elixir.BattleshipServer.Store:handle_info:23 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23 in context child_terminated
2018-03-23 10:32:15.513 [error] <0.325.0> gen_server <0.325.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:32:15.513 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:32:15.534 [error] <0.321.0> gen_server <0.321.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:32:15.534 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:32:15.534 [error] <0.319.0> Supervisor {<0.319.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.320.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.321.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:32:15.534 [error] <0.320.0> Supervisor {<0.320.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7404>, <0.321.0>, <0.323.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58323 -> 127.0.0.1:5672">>) at <0.325.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:32:15.534 [error] <0.319.0> Supervisor {<0.319.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.320.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.321.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:32:15.534 [error] <0.320.0> Supervisor {<0.320.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7404>, <0.321.0>, <0.323.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58323 -> 127.0.0.1:5672">>) at <0.325.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:34:08.613 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:34:08.664 [info] <0.33.0> Application lager started on node 'server@NT-21'
2018-03-23 10:34:08.680 [info] <0.33.0> Application xmerl started on node 'server@NT-21'
2018-03-23 10:34:08.699 [info] <0.33.0> Application jsx started on node 'server@NT-21'
2018-03-23 10:34:08.741 [info] <0.33.0> Application ranch started on node 'server@NT-21'
2018-03-23 10:34:08.752 [info] <0.33.0> Application ranch_proxy_protocol started on node 'server@NT-21'
2018-03-23 10:34:08.761 [info] <0.33.0> Application recon started on node 'server@NT-21'
2018-03-23 10:34:08.762 [info] <0.33.0> Application rabbit_common started on node 'server@NT-21'
2018-03-23 10:34:08.781 [info] <0.33.0> Application amqp_client started on node 'server@NT-21'
2018-03-23 10:34:08.782 [info] <0.33.0> Application amqp started on node 'server@NT-21'
2018-03-23 10:34:08.795 [info] <0.33.0> Application poison started on node 'server@NT-21'
2018-03-23 10:34:08.824 [info] <0.33.0> Application earmark started on node 'server@NT-21'
2018-03-23 10:34:08.825 [info] <0.33.0> Application ex_doc started on node 'server@NT-21'
2018-03-23 10:34:08.825 [info] <0.33.0> Application battleships started on node 'server@NT-21'
2018-03-23 10:34:09.229 [info] <0.33.0> Application battleship_server started on node 'server@NT-21'
2018-03-23 10:34:13.696 [error] <0.300.0> gen_server <0.300.0> terminated with reason: bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...}
2018-03-23 10:34:13.696 [error] <0.300.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...} in gen_server:handle_common_reply/8 line 730
2018-03-23 10:34:13.696 [error] <0.282.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.300.0> exit with reason bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...} in context child_terminated
2018-03-23 10:34:44.101 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:34:44.168 [info] <0.33.0> Application lager started on node 'server@NT-21'
2018-03-23 10:34:44.201 [info] <0.33.0> Application xmerl started on node 'server@NT-21'
2018-03-23 10:34:44.238 [info] <0.33.0> Application jsx started on node 'server@NT-21'
2018-03-23 10:34:44.304 [info] <0.33.0> Application ranch started on node 'server@NT-21'
2018-03-23 10:34:44.337 [info] <0.33.0> Application ranch_proxy_protocol started on node 'server@NT-21'
2018-03-23 10:34:44.355 [info] <0.33.0> Application recon started on node 'server@NT-21'
2018-03-23 10:34:44.355 [info] <0.33.0> Application rabbit_common started on node 'server@NT-21'
2018-03-23 10:34:44.390 [info] <0.33.0> Application amqp_client started on node 'server@NT-21'
2018-03-23 10:34:44.391 [info] <0.33.0> Application amqp started on node 'server@NT-21'
2018-03-23 10:34:44.406 [info] <0.33.0> Application poison started on node 'server@NT-21'
2018-03-23 10:34:44.462 [info] <0.33.0> Application earmark started on node 'server@NT-21'
2018-03-23 10:34:44.462 [info] <0.33.0> Application ex_doc started on node 'server@NT-21'
2018-03-23 10:34:44.463 [info] <0.33.0> Application battleships started on node 'server@NT-21'
2018-03-23 10:34:45.049 [info] <0.33.0> Application battleship_server started on node 'server@NT-21'
2018-03-23 10:35:39.535 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:35:39.585 [info] <0.33.0> Application lager started on node 'server@NT-21'
2018-03-23 10:35:39.604 [info] <0.33.0> Application xmerl started on node 'server@NT-21'
2018-03-23 10:35:39.624 [info] <0.33.0> Application jsx started on node 'server@NT-21'
2018-03-23 10:35:39.667 [info] <0.33.0> Application ranch started on node 'server@NT-21'
2018-03-23 10:35:39.678 [info] <0.33.0> Application ranch_proxy_protocol started on node 'server@NT-21'
2018-03-23 10:35:39.688 [info] <0.33.0> Application recon started on node 'server@NT-21'
2018-03-23 10:35:39.688 [info] <0.33.0> Application rabbit_common started on node 'server@NT-21'
2018-03-23 10:35:39.711 [info] <0.33.0> Application amqp_client started on node 'server@NT-21'
2018-03-23 10:35:39.711 [info] <0.33.0> Application amqp started on node 'server@NT-21'
2018-03-23 10:35:39.723 [info] <0.33.0> Application poison started on node 'server@NT-21'
2018-03-23 10:35:39.751 [info] <0.33.0> Application earmark started on node 'server@NT-21'
2018-03-23 10:35:39.751 [info] <0.33.0> Application ex_doc started on node 'server@NT-21'
2018-03-23 10:35:39.751 [info] <0.33.0> Application battleships started on node 'server@NT-21'
2018-03-23 10:35:40.153 [info] <0.33.0> Application battleship_server started on node 'server@NT-21'
2018-03-23 10:37:40.130 [error] <0.293.0> gen_server <0.293.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.145 [error] <0.289.0> gen_server <0.289.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.145 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.145 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.145 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.145 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7497>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58420 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.145 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7497>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58420 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.145 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.168 [error] <0.307.0> gen_server <0.307.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.169 [error] <0.303.0> gen_server <0.303.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.169 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.169 [error] <0.303.0> CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.169 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.169 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.169 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7652>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58421 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.169 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7652>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58421 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
