2018-03-23 10:31:08.110 [error] <0.182.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.187.0> exit with reason normal in context child_terminated
2018-03-23 10:31:15.560 [error] <0.291.0>@Elixir.BattleshipServer.Store:handle_info:23 gen_server <0.291.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23
2018-03-23 10:31:15.560 [error] <0.291.0>@Elixir.BattleshipServer.Store:handle_info:23 CRASH REPORT Process <0.291.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23
2018-03-23 10:31:15.560 [error] <0.273.0>@Elixir.BattleshipServer.Store:handle_info:23 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.291.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_deliver,<<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423484}">>,...}, nil) line 23 in context child_terminated
2018-03-23 10:32:15.513 [error] <0.325.0> gen_server <0.325.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:32:15.513 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:32:15.534 [error] <0.321.0> gen_server <0.321.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:32:15.534 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:32:15.534 [error] <0.319.0> Supervisor {<0.319.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.320.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.321.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:32:15.534 [error] <0.320.0> Supervisor {<0.320.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7404>, <0.321.0>, <0.323.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58323 -> 127.0.0.1:5672">>) at <0.325.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:32:15.534 [error] <0.319.0> Supervisor {<0.319.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.320.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.321.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:32:15.534 [error] <0.320.0> Supervisor {<0.320.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7404>, <0.321.0>, <0.323.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58323 -> 127.0.0.1:5672">>) at <0.325.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:34:08.613 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:34:13.696 [error] <0.300.0> gen_server <0.300.0> terminated with reason: bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...}
2018-03-23 10:34:13.696 [error] <0.300.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...} in gen_server:handle_common_reply/8 line 730
2018-03-23 10:34:13.696 [error] <0.282.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.300.0> exit with reason bad return value: #{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,source => {nil,<<"game">>},state => loaded},'__struct__' => 'Elixir.Battleshipserver.Db.Game',end_date => nil,game_id => -576460752303423037,id => 37,player1_username => <<"Alex">>,player2_username => <<"Manos">>,start_date => #{'__struct__' => 'Elixir.DateTime',calendar => 'Elixir.Calendar.ISO',day => 23,hour => 8,microsecond => {519559,6},minute => 34,month => 3,second => 13,std_offset => 0,time_zone => <<"Etc/U...">>,...},...} in context child_terminated
2018-03-23 10:34:44.101 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:35:39.535 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:37:40.130 [error] <0.293.0> gen_server <0.293.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.145 [error] <0.289.0> gen_server <0.289.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.145 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.145 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.145 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.145 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7497>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58420 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.145 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7497>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58420 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.145 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.168 [error] <0.307.0> gen_server <0.307.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.169 [error] <0.303.0> gen_server <0.303.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:37:40.169 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.169 [error] <0.303.0> CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:37:40.169 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.169 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:37:40.169 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7652>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58421 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:37:40.169 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7652>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58421 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
